### ISSUE TITLE
Issue in image tracking.

### ISSUE THREAD

**Issue by crouched** [ashish8858/Face-Recognition-Based-Attendance-System#1]
Your project really helped me with my assignment, the database collection and training went well but I am facing an issue in 'image tracking', the following error pops up, can you please guide me, will be very helpfull. Thanks in advance.
![error](https://user-images.githubusercontent.com/42216198/44308470-08be1480-a3d0-11e8-8524-7506b7d14ea0.PNG)

**Comment by crouched** [comment]
Okay I figured it out myself, there was a version-clash of opencv.

**Comment by abhinayy0** [comment]
same issue, how to solve version clash of opencv
