### ISSUE TITLE
Error while image tracking

### ISSUE THREAD

**Issue by Vrushank796** [ashish8858/Face-Recognition-Based-Attendance-System#14]
![isMap Error](https://user-images.githubusercontent.com/42446203/54522323-ee164300-4992-11e9-821b-b02f850d2f07.JPG)
 Also first you don't had tranning.yml file then i had imported this file from mayur after that now i am getting error as isMap() Node error in persistence.cpp can you help?

**Comment by mayankjamwal** [comment]
Bro i am facing the issue where the program could not store attendence thus it could not map the image to the assigned name of the individual person.

**Comment by Vrushank796** [comment]
You can find modified files at this below link in which i had added some modified files and it will be easy for you to run the working code
https://github.com/Vrushank796/Face-recognition-and-attendance-system

**Comment by mayankjamwal** [comment]
I made some changes to your code because the code you gave making the screen freeze basically it is not capturing the photo but some changes from my end making that happen but it is not recognising the image and showing a title of unknown even after training it.
